name: Create release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.23.1'
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -o docker-machine-driver-fsas .
        env:
          CGO_ENABLED: "0"
      - name: Test
        run: go test ./...
      - name: Create node driver YAML
        run: bash ./ci_tools/generate_nodedriver_yaml.sh
      - name: Upload binary and YAML
        uses: actions/upload-artifact@v4
        with:
          name: docker-machine-driver-fsas-artifact
          path: |
            docker-machine-driver-fsas
            docker-machine-driver-fsas.yml
          retention-days: 4
          if-no-files-found: warn
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            docker-machine-driver-fsas.yml
            docker-machine-driver-fsas